//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bastama_İBB_Web_Servis.iettanlikveri {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="iettanlikveri.SeferGerceklesmeSoap")]
    public interface SeferGerceklesmeSoap {
        
        // CODEGEN: Generating message contract since element name GetBozukSatih_XMLResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetBozukSatih_XML", ReplyAction="*")]
        Bastama_İBB_Web_Servis.iettanlikveri.GetBozukSatih_XMLResponse GetBozukSatih_XML(Bastama_İBB_Web_Servis.iettanlikveri.GetBozukSatih_XMLRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetBozukSatih_XML", ReplyAction="*")]
        System.Threading.Tasks.Task<Bastama_İBB_Web_Servis.iettanlikveri.GetBozukSatih_XMLResponse> GetBozukSatih_XMLAsync(Bastama_İBB_Web_Servis.iettanlikveri.GetBozukSatih_XMLRequest request);
        
        // CODEGEN: Generating message contract since element name GetBozukSatih_jsonResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetBozukSatih_json", ReplyAction="*")]
        Bastama_İBB_Web_Servis.iettanlikveri.GetBozukSatih_jsonResponse GetBozukSatih_json(Bastama_İBB_Web_Servis.iettanlikveri.GetBozukSatih_jsonRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetBozukSatih_json", ReplyAction="*")]
        System.Threading.Tasks.Task<Bastama_İBB_Web_Servis.iettanlikveri.GetBozukSatih_jsonResponse> GetBozukSatih_jsonAsync(Bastama_İBB_Web_Servis.iettanlikveri.GetBozukSatih_jsonRequest request);
        
        // CODEGEN: Generating message contract since element name GetFiloAracKonum_jsonResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetFiloAracKonum_json", ReplyAction="*")]
        Bastama_İBB_Web_Servis.iettanlikveri.GetFiloAracKonum_jsonResponse GetFiloAracKonum_json(Bastama_İBB_Web_Servis.iettanlikveri.GetFiloAracKonum_jsonRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetFiloAracKonum_json", ReplyAction="*")]
        System.Threading.Tasks.Task<Bastama_İBB_Web_Servis.iettanlikveri.GetFiloAracKonum_jsonResponse> GetFiloAracKonum_jsonAsync(Bastama_İBB_Web_Servis.iettanlikveri.GetFiloAracKonum_jsonRequest request);
        
        // CODEGEN: Generating message contract since element name Tarih from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetKazaLokasyon_XML", ReplyAction="*")]
        Bastama_İBB_Web_Servis.iettanlikveri.GetKazaLokasyon_XMLResponse GetKazaLokasyon_XML(Bastama_İBB_Web_Servis.iettanlikveri.GetKazaLokasyon_XMLRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetKazaLokasyon_XML", ReplyAction="*")]
        System.Threading.Tasks.Task<Bastama_İBB_Web_Servis.iettanlikveri.GetKazaLokasyon_XMLResponse> GetKazaLokasyon_XMLAsync(Bastama_İBB_Web_Servis.iettanlikveri.GetKazaLokasyon_XMLRequest request);
        
        // CODEGEN: Generating message contract since element name Tarih from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetKazaLokasyon_json", ReplyAction="*")]
        Bastama_İBB_Web_Servis.iettanlikveri.GetKazaLokasyon_jsonResponse GetKazaLokasyon_json(Bastama_İBB_Web_Servis.iettanlikveri.GetKazaLokasyon_jsonRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetKazaLokasyon_json", ReplyAction="*")]
        System.Threading.Tasks.Task<Bastama_İBB_Web_Servis.iettanlikveri.GetKazaLokasyon_jsonResponse> GetKazaLokasyon_jsonAsync(Bastama_İBB_Web_Servis.iettanlikveri.GetKazaLokasyon_jsonRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetBozukSatih_XMLRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetBozukSatih_XML", Namespace="http://tempuri.org/", Order=0)]
        public Bastama_İBB_Web_Servis.iettanlikveri.GetBozukSatih_XMLRequestBody Body;
        
        public GetBozukSatih_XMLRequest() {
        }
        
        public GetBozukSatih_XMLRequest(Bastama_İBB_Web_Servis.iettanlikveri.GetBozukSatih_XMLRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetBozukSatih_XMLRequestBody {
        
        public GetBozukSatih_XMLRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetBozukSatih_XMLResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetBozukSatih_XMLResponse", Namespace="http://tempuri.org/", Order=0)]
        public Bastama_İBB_Web_Servis.iettanlikveri.GetBozukSatih_XMLResponseBody Body;
        
        public GetBozukSatih_XMLResponse() {
        }
        
        public GetBozukSatih_XMLResponse(Bastama_İBB_Web_Servis.iettanlikveri.GetBozukSatih_XMLResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetBozukSatih_XMLResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement GetBozukSatih_XMLResult;
        
        public GetBozukSatih_XMLResponseBody() {
        }
        
        public GetBozukSatih_XMLResponseBody(System.Xml.Linq.XElement GetBozukSatih_XMLResult) {
            this.GetBozukSatih_XMLResult = GetBozukSatih_XMLResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetBozukSatih_jsonRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetBozukSatih_json", Namespace="http://tempuri.org/", Order=0)]
        public Bastama_İBB_Web_Servis.iettanlikveri.GetBozukSatih_jsonRequestBody Body;
        
        public GetBozukSatih_jsonRequest() {
        }
        
        public GetBozukSatih_jsonRequest(Bastama_İBB_Web_Servis.iettanlikveri.GetBozukSatih_jsonRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetBozukSatih_jsonRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int saat;
        
        public GetBozukSatih_jsonRequestBody() {
        }
        
        public GetBozukSatih_jsonRequestBody(int saat) {
            this.saat = saat;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetBozukSatih_jsonResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetBozukSatih_jsonResponse", Namespace="http://tempuri.org/", Order=0)]
        public Bastama_İBB_Web_Servis.iettanlikveri.GetBozukSatih_jsonResponseBody Body;
        
        public GetBozukSatih_jsonResponse() {
        }
        
        public GetBozukSatih_jsonResponse(Bastama_İBB_Web_Servis.iettanlikveri.GetBozukSatih_jsonResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetBozukSatih_jsonResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetBozukSatih_jsonResult;
        
        public GetBozukSatih_jsonResponseBody() {
        }
        
        public GetBozukSatih_jsonResponseBody(string GetBozukSatih_jsonResult) {
            this.GetBozukSatih_jsonResult = GetBozukSatih_jsonResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetFiloAracKonum_jsonRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetFiloAracKonum_json", Namespace="http://tempuri.org/", Order=0)]
        public Bastama_İBB_Web_Servis.iettanlikveri.GetFiloAracKonum_jsonRequestBody Body;
        
        public GetFiloAracKonum_jsonRequest() {
        }
        
        public GetFiloAracKonum_jsonRequest(Bastama_İBB_Web_Servis.iettanlikveri.GetFiloAracKonum_jsonRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetFiloAracKonum_jsonRequestBody {
        
        public GetFiloAracKonum_jsonRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetFiloAracKonum_jsonResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetFiloAracKonum_jsonResponse", Namespace="http://tempuri.org/", Order=0)]
        public Bastama_İBB_Web_Servis.iettanlikveri.GetFiloAracKonum_jsonResponseBody Body;
        
        public GetFiloAracKonum_jsonResponse() {
        }
        
        public GetFiloAracKonum_jsonResponse(Bastama_İBB_Web_Servis.iettanlikveri.GetFiloAracKonum_jsonResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetFiloAracKonum_jsonResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetFiloAracKonum_jsonResult;
        
        public GetFiloAracKonum_jsonResponseBody() {
        }
        
        public GetFiloAracKonum_jsonResponseBody(string GetFiloAracKonum_jsonResult) {
            this.GetFiloAracKonum_jsonResult = GetFiloAracKonum_jsonResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetKazaLokasyon_XMLRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetKazaLokasyon_XML", Namespace="http://tempuri.org/", Order=0)]
        public Bastama_İBB_Web_Servis.iettanlikveri.GetKazaLokasyon_XMLRequestBody Body;
        
        public GetKazaLokasyon_XMLRequest() {
        }
        
        public GetKazaLokasyon_XMLRequest(Bastama_İBB_Web_Servis.iettanlikveri.GetKazaLokasyon_XMLRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetKazaLokasyon_XMLRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Tarih;
        
        public GetKazaLokasyon_XMLRequestBody() {
        }
        
        public GetKazaLokasyon_XMLRequestBody(string Tarih) {
            this.Tarih = Tarih;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetKazaLokasyon_XMLResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetKazaLokasyon_XMLResponse", Namespace="http://tempuri.org/", Order=0)]
        public Bastama_İBB_Web_Servis.iettanlikveri.GetKazaLokasyon_XMLResponseBody Body;
        
        public GetKazaLokasyon_XMLResponse() {
        }
        
        public GetKazaLokasyon_XMLResponse(Bastama_İBB_Web_Servis.iettanlikveri.GetKazaLokasyon_XMLResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetKazaLokasyon_XMLResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement GetKazaLokasyon_XMLResult;
        
        public GetKazaLokasyon_XMLResponseBody() {
        }
        
        public GetKazaLokasyon_XMLResponseBody(System.Xml.Linq.XElement GetKazaLokasyon_XMLResult) {
            this.GetKazaLokasyon_XMLResult = GetKazaLokasyon_XMLResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetKazaLokasyon_jsonRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetKazaLokasyon_json", Namespace="http://tempuri.org/", Order=0)]
        public Bastama_İBB_Web_Servis.iettanlikveri.GetKazaLokasyon_jsonRequestBody Body;
        
        public GetKazaLokasyon_jsonRequest() {
        }
        
        public GetKazaLokasyon_jsonRequest(Bastama_İBB_Web_Servis.iettanlikveri.GetKazaLokasyon_jsonRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetKazaLokasyon_jsonRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Tarih;
        
        public GetKazaLokasyon_jsonRequestBody() {
        }
        
        public GetKazaLokasyon_jsonRequestBody(string Tarih) {
            this.Tarih = Tarih;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetKazaLokasyon_jsonResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetKazaLokasyon_jsonResponse", Namespace="http://tempuri.org/", Order=0)]
        public Bastama_İBB_Web_Servis.iettanlikveri.GetKazaLokasyon_jsonResponseBody Body;
        
        public GetKazaLokasyon_jsonResponse() {
        }
        
        public GetKazaLokasyon_jsonResponse(Bastama_İBB_Web_Servis.iettanlikveri.GetKazaLokasyon_jsonResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetKazaLokasyon_jsonResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetKazaLokasyon_jsonResult;
        
        public GetKazaLokasyon_jsonResponseBody() {
        }
        
        public GetKazaLokasyon_jsonResponseBody(string GetKazaLokasyon_jsonResult) {
            this.GetKazaLokasyon_jsonResult = GetKazaLokasyon_jsonResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SeferGerceklesmeSoapChannel : Bastama_İBB_Web_Servis.iettanlikveri.SeferGerceklesmeSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SeferGerceklesmeSoapClient : System.ServiceModel.ClientBase<Bastama_İBB_Web_Servis.iettanlikveri.SeferGerceklesmeSoap>, Bastama_İBB_Web_Servis.iettanlikveri.SeferGerceklesmeSoap {
        
        public SeferGerceklesmeSoapClient() {
        }
        
        public SeferGerceklesmeSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SeferGerceklesmeSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SeferGerceklesmeSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SeferGerceklesmeSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Bastama_İBB_Web_Servis.iettanlikveri.GetBozukSatih_XMLResponse Bastama_İBB_Web_Servis.iettanlikveri.SeferGerceklesmeSoap.GetBozukSatih_XML(Bastama_İBB_Web_Servis.iettanlikveri.GetBozukSatih_XMLRequest request) {
            return base.Channel.GetBozukSatih_XML(request);
        }
        
        public System.Xml.Linq.XElement GetBozukSatih_XML() {
            Bastama_İBB_Web_Servis.iettanlikveri.GetBozukSatih_XMLRequest inValue = new Bastama_İBB_Web_Servis.iettanlikveri.GetBozukSatih_XMLRequest();
            inValue.Body = new Bastama_İBB_Web_Servis.iettanlikveri.GetBozukSatih_XMLRequestBody();
            Bastama_İBB_Web_Servis.iettanlikveri.GetBozukSatih_XMLResponse retVal = ((Bastama_İBB_Web_Servis.iettanlikveri.SeferGerceklesmeSoap)(this)).GetBozukSatih_XML(inValue);
            return retVal.Body.GetBozukSatih_XMLResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Bastama_İBB_Web_Servis.iettanlikveri.GetBozukSatih_XMLResponse> Bastama_İBB_Web_Servis.iettanlikveri.SeferGerceklesmeSoap.GetBozukSatih_XMLAsync(Bastama_İBB_Web_Servis.iettanlikveri.GetBozukSatih_XMLRequest request) {
            return base.Channel.GetBozukSatih_XMLAsync(request);
        }
        
        public System.Threading.Tasks.Task<Bastama_İBB_Web_Servis.iettanlikveri.GetBozukSatih_XMLResponse> GetBozukSatih_XMLAsync() {
            Bastama_İBB_Web_Servis.iettanlikveri.GetBozukSatih_XMLRequest inValue = new Bastama_İBB_Web_Servis.iettanlikveri.GetBozukSatih_XMLRequest();
            inValue.Body = new Bastama_İBB_Web_Servis.iettanlikveri.GetBozukSatih_XMLRequestBody();
            return ((Bastama_İBB_Web_Servis.iettanlikveri.SeferGerceklesmeSoap)(this)).GetBozukSatih_XMLAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Bastama_İBB_Web_Servis.iettanlikveri.GetBozukSatih_jsonResponse Bastama_İBB_Web_Servis.iettanlikveri.SeferGerceklesmeSoap.GetBozukSatih_json(Bastama_İBB_Web_Servis.iettanlikveri.GetBozukSatih_jsonRequest request) {
            return base.Channel.GetBozukSatih_json(request);
        }
        
        public string GetBozukSatih_json(int saat) {
            Bastama_İBB_Web_Servis.iettanlikveri.GetBozukSatih_jsonRequest inValue = new Bastama_İBB_Web_Servis.iettanlikveri.GetBozukSatih_jsonRequest();
            inValue.Body = new Bastama_İBB_Web_Servis.iettanlikveri.GetBozukSatih_jsonRequestBody();
            inValue.Body.saat = saat;
            Bastama_İBB_Web_Servis.iettanlikveri.GetBozukSatih_jsonResponse retVal = ((Bastama_İBB_Web_Servis.iettanlikveri.SeferGerceklesmeSoap)(this)).GetBozukSatih_json(inValue);
            return retVal.Body.GetBozukSatih_jsonResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Bastama_İBB_Web_Servis.iettanlikveri.GetBozukSatih_jsonResponse> Bastama_İBB_Web_Servis.iettanlikveri.SeferGerceklesmeSoap.GetBozukSatih_jsonAsync(Bastama_İBB_Web_Servis.iettanlikveri.GetBozukSatih_jsonRequest request) {
            return base.Channel.GetBozukSatih_jsonAsync(request);
        }
        
        public System.Threading.Tasks.Task<Bastama_İBB_Web_Servis.iettanlikveri.GetBozukSatih_jsonResponse> GetBozukSatih_jsonAsync(int saat) {
            Bastama_İBB_Web_Servis.iettanlikveri.GetBozukSatih_jsonRequest inValue = new Bastama_İBB_Web_Servis.iettanlikveri.GetBozukSatih_jsonRequest();
            inValue.Body = new Bastama_İBB_Web_Servis.iettanlikveri.GetBozukSatih_jsonRequestBody();
            inValue.Body.saat = saat;
            return ((Bastama_İBB_Web_Servis.iettanlikveri.SeferGerceklesmeSoap)(this)).GetBozukSatih_jsonAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Bastama_İBB_Web_Servis.iettanlikveri.GetFiloAracKonum_jsonResponse Bastama_İBB_Web_Servis.iettanlikveri.SeferGerceklesmeSoap.GetFiloAracKonum_json(Bastama_İBB_Web_Servis.iettanlikveri.GetFiloAracKonum_jsonRequest request) {
            return base.Channel.GetFiloAracKonum_json(request);
        }
        
        public string GetFiloAracKonum_json() {
            Bastama_İBB_Web_Servis.iettanlikveri.GetFiloAracKonum_jsonRequest inValue = new Bastama_İBB_Web_Servis.iettanlikveri.GetFiloAracKonum_jsonRequest();
            inValue.Body = new Bastama_İBB_Web_Servis.iettanlikveri.GetFiloAracKonum_jsonRequestBody();
            Bastama_İBB_Web_Servis.iettanlikveri.GetFiloAracKonum_jsonResponse retVal = ((Bastama_İBB_Web_Servis.iettanlikveri.SeferGerceklesmeSoap)(this)).GetFiloAracKonum_json(inValue);
            return retVal.Body.GetFiloAracKonum_jsonResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Bastama_İBB_Web_Servis.iettanlikveri.GetFiloAracKonum_jsonResponse> Bastama_İBB_Web_Servis.iettanlikveri.SeferGerceklesmeSoap.GetFiloAracKonum_jsonAsync(Bastama_İBB_Web_Servis.iettanlikveri.GetFiloAracKonum_jsonRequest request) {
            return base.Channel.GetFiloAracKonum_jsonAsync(request);
        }
        
        public System.Threading.Tasks.Task<Bastama_İBB_Web_Servis.iettanlikveri.GetFiloAracKonum_jsonResponse> GetFiloAracKonum_jsonAsync() {
            Bastama_İBB_Web_Servis.iettanlikveri.GetFiloAracKonum_jsonRequest inValue = new Bastama_İBB_Web_Servis.iettanlikveri.GetFiloAracKonum_jsonRequest();
            inValue.Body = new Bastama_İBB_Web_Servis.iettanlikveri.GetFiloAracKonum_jsonRequestBody();
            return ((Bastama_İBB_Web_Servis.iettanlikveri.SeferGerceklesmeSoap)(this)).GetFiloAracKonum_jsonAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Bastama_İBB_Web_Servis.iettanlikveri.GetKazaLokasyon_XMLResponse Bastama_İBB_Web_Servis.iettanlikveri.SeferGerceklesmeSoap.GetKazaLokasyon_XML(Bastama_İBB_Web_Servis.iettanlikveri.GetKazaLokasyon_XMLRequest request) {
            return base.Channel.GetKazaLokasyon_XML(request);
        }
        
        public System.Xml.Linq.XElement GetKazaLokasyon_XML(string Tarih) {
            Bastama_İBB_Web_Servis.iettanlikveri.GetKazaLokasyon_XMLRequest inValue = new Bastama_İBB_Web_Servis.iettanlikveri.GetKazaLokasyon_XMLRequest();
            inValue.Body = new Bastama_İBB_Web_Servis.iettanlikveri.GetKazaLokasyon_XMLRequestBody();
            inValue.Body.Tarih = Tarih;
            Bastama_İBB_Web_Servis.iettanlikveri.GetKazaLokasyon_XMLResponse retVal = ((Bastama_İBB_Web_Servis.iettanlikveri.SeferGerceklesmeSoap)(this)).GetKazaLokasyon_XML(inValue);
            return retVal.Body.GetKazaLokasyon_XMLResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Bastama_İBB_Web_Servis.iettanlikveri.GetKazaLokasyon_XMLResponse> Bastama_İBB_Web_Servis.iettanlikveri.SeferGerceklesmeSoap.GetKazaLokasyon_XMLAsync(Bastama_İBB_Web_Servis.iettanlikveri.GetKazaLokasyon_XMLRequest request) {
            return base.Channel.GetKazaLokasyon_XMLAsync(request);
        }
        
        public System.Threading.Tasks.Task<Bastama_İBB_Web_Servis.iettanlikveri.GetKazaLokasyon_XMLResponse> GetKazaLokasyon_XMLAsync(string Tarih) {
            Bastama_İBB_Web_Servis.iettanlikveri.GetKazaLokasyon_XMLRequest inValue = new Bastama_İBB_Web_Servis.iettanlikveri.GetKazaLokasyon_XMLRequest();
            inValue.Body = new Bastama_İBB_Web_Servis.iettanlikveri.GetKazaLokasyon_XMLRequestBody();
            inValue.Body.Tarih = Tarih;
            return ((Bastama_İBB_Web_Servis.iettanlikveri.SeferGerceklesmeSoap)(this)).GetKazaLokasyon_XMLAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Bastama_İBB_Web_Servis.iettanlikveri.GetKazaLokasyon_jsonResponse Bastama_İBB_Web_Servis.iettanlikveri.SeferGerceklesmeSoap.GetKazaLokasyon_json(Bastama_İBB_Web_Servis.iettanlikveri.GetKazaLokasyon_jsonRequest request) {
            return base.Channel.GetKazaLokasyon_json(request);
        }
        
        public string GetKazaLokasyon_json(string Tarih) {
            Bastama_İBB_Web_Servis.iettanlikveri.GetKazaLokasyon_jsonRequest inValue = new Bastama_İBB_Web_Servis.iettanlikveri.GetKazaLokasyon_jsonRequest();
            inValue.Body = new Bastama_İBB_Web_Servis.iettanlikveri.GetKazaLokasyon_jsonRequestBody();
            inValue.Body.Tarih = Tarih;
            Bastama_İBB_Web_Servis.iettanlikveri.GetKazaLokasyon_jsonResponse retVal = ((Bastama_İBB_Web_Servis.iettanlikveri.SeferGerceklesmeSoap)(this)).GetKazaLokasyon_json(inValue);
            return retVal.Body.GetKazaLokasyon_jsonResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Bastama_İBB_Web_Servis.iettanlikveri.GetKazaLokasyon_jsonResponse> Bastama_İBB_Web_Servis.iettanlikveri.SeferGerceklesmeSoap.GetKazaLokasyon_jsonAsync(Bastama_İBB_Web_Servis.iettanlikveri.GetKazaLokasyon_jsonRequest request) {
            return base.Channel.GetKazaLokasyon_jsonAsync(request);
        }
        
        public System.Threading.Tasks.Task<Bastama_İBB_Web_Servis.iettanlikveri.GetKazaLokasyon_jsonResponse> GetKazaLokasyon_jsonAsync(string Tarih) {
            Bastama_İBB_Web_Servis.iettanlikveri.GetKazaLokasyon_jsonRequest inValue = new Bastama_İBB_Web_Servis.iettanlikveri.GetKazaLokasyon_jsonRequest();
            inValue.Body = new Bastama_İBB_Web_Servis.iettanlikveri.GetKazaLokasyon_jsonRequestBody();
            inValue.Body.Tarih = Tarih;
            return ((Bastama_İBB_Web_Servis.iettanlikveri.SeferGerceklesmeSoap)(this)).GetKazaLokasyon_jsonAsync(inValue);
        }
    }
}
